tuple_a = (3,1,2,4)
print(tuple_a)
tuple_b = (5,7,6,8)
print(tuple_b)
tuple_c = tuple(tuple_a + tuple_b)
print(tuple_c)
tuple_d = tuple(sorted(tuple_c))
print(tuple_d)
print(f"Phần tử thứ 3 của d: {tuple_d[2]}")
print(f"3 phần tử cuối cùng của d: {tuple_d[-3:]}")
