tuple_data = ("red", "green", "yellow", "blue", "black", "white", "pink", "orange", "red", "blue")
index_positive = int(input("Nhập số từ 0 đến 9: "))
index_negative = int(input("Nhập số từ 1 đến 9: "))
search_string = input("Nhập chuỗi cần tìm: ")
print(f"Tuple: {tuple_data}")
print(f"Tuple[{index_positive}] = {tuple_data[index_positive]}")
print(f"Tuple[{index_negative}] = {tuple_data[index_negative]}")
count_search_string = tuple_data.count(search_string)
print(f"{search_string} xuất hiện trong tuple {count_search_string} lần")